import{S as $,i as y,a as C}from"./assets/vendor-b42c18af.js";(function(){const o=document.createElement("link").relList;if(o&&o.supports&&o.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))a(t);new MutationObserver(t=>{for(const s of t)if(s.type==="childList")for(const i of s.addedNodes)i.tagName==="LINK"&&i.rel==="modulepreload"&&a(i)}).observe(document,{childList:!0,subtree:!0});function r(t){const s={};return t.integrity&&(s.integrity=t.integrity),t.referrerPolicy&&(s.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?s.credentials="include":t.crossOrigin==="anonymous"?s.credentials="omit":s.credentials="same-origin",s}function a(t){if(t.ep)return;t.ep=!0;const s=r(t);fetch(t.href,s)}})();const l=document.querySelector(".gallery"),p=document.querySelector(".search-form"),c=document.querySelector(".loader");let n;const h="gallery-link";let m=1,d="",f=0;c.style.display="none";const L=new $(`.${h}`);p.addEventListener("submit",async function(e){if(e.preventDefault(),d=e.target.elements.search.value.trim(),d===""){u("Please enter a search query");return}m=1,l.innerHTML="",M();try{const{data:o}=await v(d,m),{hits:r,total:a}=o;if(f=a,r.length>0){const t=r.map(E).join("");l.innerHTML=t,F(`Was found: ${f} images`),p.reset(),L.refresh(),g()}else u("Sorry, there are no images matching your search query. Please try again!")}catch(o){u(`Error fetching images: ${o}`)}finally{O()}});async function w(){c.style.display="block",m++;try{const{data:e}=await v(d,m),{hits:o}=e;if(o.length>0){const r=o.map(E).join("");l.insertAdjacentHTML("beforeend",r),L.refresh(),g(),H()}else g()}catch(e){u(`Error fetching more images: ${e}`)}finally{c.style.display="none"}}function S(){n=document.createElement("button"),n.classList.add("load-more-btn"),n.textContent="Load more",l.after(n),n.addEventListener("click",w)}const b={titleColor:"#FFFFFF",messageColor:"#FFFFFF",messageSize:"16px",position:"topRight",displayMode:"replace",closeOnEscape:!0,pauseOnHover:!1,maxWidth:432,messageLineHeight:"24px"};function u(e){y.show({message:e,backgroundColor:"#EF4040",progressBarColor:"#FFE0AC",icon:"icon-close",...b})}function F(e){y.show({message:e,backgroundColor:"#59A10D",progressBarColor:"#B5EA7C",icon:"icon-check",...b})}function M(){c.style.display="block"}function O(){c.style.display="none"}function g(){document.querySelectorAll(".gallery-image").length>=f?(n&&(n.style.display="none"),F("We're sorry, but you've reached the end of search results.")):n||S()}function H(){const e=l.lastElementChild;window.scrollTo({top:e.offsetTop+e.offsetHeight,behavior:"smooth"})}const T="https://pixabay.com/api/";async function v(e,o){const r=new URLSearchParams({key:"42205340-8125de1ae06f98e0344d3d2b5",q:e,image_type:"photo",orientation:"horizontal",safesearch:!0,page:o,per_page:15}),a=`${T}?${r}`;return C.get(a)}function E({largeImageURL:e,tags:o,webformatURL:r,likes:a,views:t,comments:s,downloads:i}){return`
  <a href="${e}" class="${h}">
    <figure>
      <img src="${r}" alt="${o}" class="gallery-image">
      <figcaption class="gallery__figcaption">
        <div class="image-item">Likes <span class="image-elem">${a}</span></div>
        <div class="image-item">Views <span class="image-elem">${t}</span></div>
        <div class="image-item">Comments <span class="image-elem">${s}</span></div>
        <div class="image-item">Downloads <span class="image-elem">${i}</span></div>
      </figcaption>
    </figure>
  </a>
`}
//# sourceMappingURL=commonHelpers.js.map
