import{S as p,i as y,a as v}from"./assets/vendor-b42c18af.js";(function(){const o=document.createElement("link").relList;if(o&&o.supports&&o.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))a(e);new MutationObserver(e=>{for(const s of e)if(s.type==="childList")for(const l of s.addedNodes)l.tagName==="LINK"&&l.rel==="modulepreload"&&a(l)}).observe(document,{childList:!0,subtree:!0});function r(e){const s={};return e.integrity&&(s.integrity=e.integrity),e.referrerPolicy&&(s.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?s.credentials="include":e.crossOrigin==="anonymous"?s.credentials="omit":s.credentials="same-origin",s}function a(e){if(e.ep)return;e.ep=!0;const s=r(e);fetch(e.href,s)}})();const c=document.querySelector(".gallery"),E=document.querySelector(".search-form"),i=document.querySelector(".loader"),n=document.createElement("button");n.classList.add("load-more-btn");n.textContent="Load more";c.after(n);const g="gallery-link";let d=1,m="",h=0;i.style.display="none";E.addEventListener("submit",async function(t){if(t.preventDefault(),m=t.target.elements.search.value.trim(),m!==""){d=1,c.innerHTML="",i.style.display="block";try{const{data:o}=await b(m,d),{hits:r,total:a}=o;if(h=a,r.length>0){const e=r.map(F).join("");c.innerHTML=e,$(`Was found: ${a} images`),new p(`.${g}`).refresh(),f(),i.style.display="none"}else u("Sorry, there are no images matching your search query. Please try again!"),n.style.display="none"}catch(o){u(`Error fetching images: ${o}`)}finally{i.style.display="none"}}});n.addEventListener("click",async function(){i.style.display="block",d++;try{const{data:t}=await b(m,d),{hits:o}=t;if(o.length>0){const r=o.map(F).join("");c.innerHTML+=r,new p(`.${g}`).refresh(),f(),C()}else f()}catch(t){u(`Error fetching more images: ${t}`)}finally{i.style.display="none"}});const L={titleColor:"#FFFFFF",messageColor:"#FFFFFF",messageSize:"16px",position:"topRight",displayMode:"replace",closeOnEscape:!0,pauseOnHover:!1,maxWidth:432,messageLineHeight:"24px"};function u(t){y.show({message:t,backgroundColor:"#EF4040",progressBarColor:"#FFE0AC",icon:"icon-close",...L})}function $(t){y.show({message:t,backgroundColor:"#59A10D",progressBarColor:"#B5EA7C",icon:"icon-check",...L})}function f(){h<=d*15?(n.style.display="none",toastInfo("We're sorry, but you've reached the end of search results.")):n.style.display="block"}function C(){const t=c.lastElementChild;window.scrollTo({top:t.offsetTop+t.offsetHeight,behavior:"smooth"})}const w="https://pixabay.com/api/";async function b(t,o){const r=new URLSearchParams({key:"42205340-8125de1ae06f98e0344d3d2b5",q:t,image_type:"photo",orientation:"horizontal",safesearch:!0,page:o,per_page:15}),a=`${w}?${r}`;return v.get(a)}function F({largeImageURL:t,tags:o,webformatURL:r,likes:a,views:e,comments:s,downloads:l}){return`
  <a href="${t}" class="${g}">
    <figure>
      <img src="${r}" alt="${o}" class="gallery-image">
      <figcaption class="gallery__figcaption">
        <div class="image-item">Likes <span class="image-elem">${a}</span></div>
        <div class="image-item">Views <span class="image-elem">${e}</span></div>
        <div class="image-item">Comments <span class="image-elem">${s}</span></div>
        <div class="image-item">Downloads <span class="image-elem">${l}</span></div>
      </figcaption>
    </figure>
  </a>
`}
//# sourceMappingURL=commonHelpers.js.map
